import { Inter, Raleway } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Provider from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'AssessAI | Smart Assessment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <Provider>
        <body className={raleway.className}  >
          {children}
        </body>
      </Provider>
    </html>
  )
}
